### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by kotamichael** [brandiqa/message-app#1]
I tried to download the demo to try it out and got the following message from Git:

> Permission denied (publickey).
>fatal: Could not read from remote repository.
>Please make sure you have the correct access rights
>and the repository exists.

**Comment by brandiqa** [comment]
This is a github issue, nothing to do with the project. You can read more about your error here: https://help.github.com/articles/error-permission-denied-publickey/. Alternatively, you can just download the project as a zip file
